//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desktop_Auth.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class IdentificationData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IdentificationData()
        {
            this.InstalledEquipments = new HashSet<InstalledEquipment>();
        }
    
        public int Code { get; set; }
        public string Serialnumber { get; set; }
        public string Inventorynumber { get; set; }
        public string IPaddres { get; set; }
        public string MACaddres { get; set; }
        public string Phonenumber { get; set; }
        public string Nameequipment { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InstalledEquipment> InstalledEquipments { get; set; }
    }
}
