//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desktop_Auth.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Infromationlocation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Infromationlocation()
        {
            this.InstalledEquipments = new HashSet<InstalledEquipment>();
        }
    
        public int Code { get; set; }
        public string Installationaddres { get; set; }
        public string Connectionpoint { get; set; }
        public string Installationlocation { get; set; }
        public string Installationdate { get; set; }
        public string GatewayPhoneNumber { get; set; }
        public string Phonelist { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InstalledEquipment> InstalledEquipments { get; set; }
    }
}
