//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desktop_Auth.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class st2_Sokolov_telecomEntities : DbContext
    {
        public st2_Sokolov_telecomEntities()
            : base("name=st2_Sokolov_telecomEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Autorization> Autorizations { get; set; }
        public virtual DbSet<IdentificationData> IdentificationDatas { get; set; }
        public virtual DbSet<Infromationlocation> Infromationlocations { get; set; }
        public virtual DbSet<InstalledEquipment> InstalledEquipments { get; set; }
        public virtual DbSet<Subscriber> Subscribers { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TypeEquipment> TypeEquipments { get; set; }
        public virtual DbSet<TypePort> TypePorts { get; set; }
    }
}
