//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desktop_Auth.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypePort
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TypePort()
        {
            this.InstalledEquipments = new HashSet<InstalledEquipment>();
        }
    
        public int Code { get; set; }
        public int IDSubscriber { get; set; }
        public string Numberport { get; set; }
        public string Typeport1 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InstalledEquipment> InstalledEquipments { get; set; }
        public virtual Subscriber Subscriber { get; set; }
    }
}
